development: &dev
  secret_key_base: 7f4974f91980cd84d2f38b2188c20d61114e72a612e2290a99bcf48c841eb1f0644eef68c154ea0a213b4a12dc8beb2843737a4a783b6aa60b988e128b2c6ccb

  telegram:
    bot:
      token: BOT_TOKEN
      username: BOT_NAME
      # async: true
      # botan:
      #   token: botan_token
      #   # async: true

test:
  secret_key_base: e19c00c2cde1a2695ba1c98352409788ea66352b90605c3ca6495ba4653cd67866da6d682fb7179d5bc4239deedda1924b5477d60327be5afcd6b3a0bfdab00c

  telegram:
    bot:
      token: test_bot_token
      username: BOT_NAME

production:
  <<: *dev
